ALLOW_MISSING_DEPENDENCIES := true

TARGET_ARCH:= arm64
TARGET_ARCH_VARIANT:= armv8-a
TARGET_CPU_VARIANT:= generic
TARGET_CPU_ABI:= arm64-v8a
TARGET_CPU_VARIANT_RUNTIME:= kryo660

TARGET_2ND_ARCH:= arm
TARGET_2ND_CPU_ABI:= 

BOARD_VENDOR:= oneplus

